# GNU ls and dircolors, install with `brew install core-utils` on MacOS
alias ls='gls --color=auto'
eval `gdircolors ~/workplace/curly-invention/dircolors/dircolors.dark`

# Vim as default editor
export EDITOR=vim

# Add to $PATH
export PATH=/usr/local/bin:$PATH
# export PATH=$HOME/workplace/local/bin:$PATH LD_LIBRARY_PATH=$HOME/workplace/local/lib:$LD_LIBRARY_PATH

# Fzf Setup
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

# Stuff I won't share
source ~/workplace/curly-invention/private/dotfiles/bash_profile
