" Autoinstall vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall
endif

" Plugins via Vim-Plug
call plug#begin('~/.vim/plugged')
" Functional Plugins
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'

" UI Plugins
Plug 'altercation/vim-colors-solarized'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'mhinz/vim-signify'

" Syntax Highlighting Plugins
Plug 'tmux-plugins/vim-tmux'
call plug#end()

" Remove any trailing whitespace that is in the file
autocmd BufRead,BufWrite * if ! &bin | silent! %s/\s\+$//ge | endif

" Autosave for .md files
autocmd BufNewFile,BufRead *.md :autocmd TextChanged,InsertLeave <buffer> silent write

" Colorscheme
filetype on
syntax enable
set background=dark
colorscheme solarized

" General Settings
set nocompatible    " Disable backward compatibility with Vi
set hidden          " Hide buffers instead of closing
set lazyredraw      " Speed up on large files
set number          " Show line numbers
set backspace=2     " Backspace through anything in insert mode
set conceallevel=0  " Do not conceal any characters
set updatetime=250  " Quicker updates
set noesckeys   " No delays for escape

" General Mappings
map <C-k> {
map <C-j> }

" Status Line
set laststatus=2    " Always show status line
set showcmd         " Always show current command

" Sign Gutter
highlight clear SignColumn

" Indentation
set expandtab       " Replace <Tab> with spaces
set shiftround      " Round indent to multiple of 'shiftwidth' (for << and >>)
set tabstop=2
set shiftwidth=2

" Search
set incsearch       " Start searching before pressing enter
set ignorecase      " Ignore case of letters
set smartcase       " Override the 'ignorecase' when there is uppercase letters
set hlsearch        " Search highlighting
nnoremap <silent> <Leader><Esc> :nohlsearch<CR>

" Buffer Control
nmap <C-h> :bp<CR>
nmap <C-l> :bn<CR>
nmap <Leader>dd :bd<CR>

" Explore Control
nmap <Leader>fe :Explore<CR>
let g:netrw_liststyle=3

" Airline Setup
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#hunks#enabled=0

" Fzf Setup
nmap <Leader>ff :Files<CR>
